<!doctype html>
<html lang="{{ app()->getLocale() }}" dir="{{ app()->isLocale('ar') ? 'rtl' : 'ltr' }}"><head><meta charset="utf-8"><style>
@page{margin:9mm 10mm 9mm}*{box-sizing:border-box}body{font-family:DejaVu Sans,sans-serif;color:#13233f;font-size:7.5px;margin:0}table{width:100%;border-collapse:collapse;table-layout:fixed}.report-head{margin:0 0 12px;border-bottom:2px solid #2563c9;table-layout:fixed}.report-head td{border:0;height:82px;padding:0 0 9px;vertical-align:middle}.report-head .date{width:16%;text-align:left;color:#31598d}.date span{display:block;font-size:7px;letter-spacing:.5px}.date strong{display:block;font-size:10px;margin-top:3px}.report-head .title{width:68%;text-align:center;color:#174fae;font-size:22px;font-weight:bold;line-height:1.35}.report-head .logo-cell{width:16%;text-align:right}.logo{display:inline-block;width:66px;height:66px;border:2px solid #2563c9;border-radius:50%;text-align:center;color:#2563c9;font-weight:bold;line-height:62px}.logo img{width:62px;height:62px;border-radius:50%}.data-table th,.data-table td{border:1px solid #2563c9;padding:6px 2px;text-align:center;vertical-align:middle;line-height:1.35}.data-table th{background:#eaf2ff;color:#123f85;font-weight:bold;font-size:6.5px}.data-table td{height:30px}.index{width:3%}.month{width:7%}.company{width:9%}.business{width:8%}.admin{width:8%}.location{width:6%}.refs{width:10%}.money{width:7%}.rate{width:6%}.total{width:8%}.received{width:7%}.returned{width:9%}.notes{width:12%}.summary{margin-top:12px;width:100%;border-collapse:collapse}.summary td{border:1px solid #b9ccef;background:#f7faff;padding:8px;text-align:center}.summary span{display:block;color:#5a6c86;font-size:7px}.summary strong{display:block;color:#123f85;font-size:10px;margin-top:3px}.footer{position:fixed;bottom:-2mm;left:0;right:0;border-top:1px solid #c9d7ed;padding-top:4px;color:#73829a;font-size:6px}.footer .left{float:left}.footer .right{float:right}
</style></head><body>
@php
    $month = (int) ($filters['month'] ?? 0); $year = $filters['year'] ?? null;
    $period = $month ? 'for '.DateTime::createFromFormat('!m', $month)->format('F').($year ? ' '.$year : '') : ($year ? 'for '.$year : '- All Periods');
    $arabicMonths = [1=>'يناير',2=>'فبراير',3=>'مارس',4=>'أبريل',5=>'مايو',6=>'يونيو',7=>'يوليو',8=>'أغسطس',9=>'سبتمبر',10=>'أكتوبر',11=>'نوفمبر',12=>'ديسمبر'];
    $arabicPeriod = $month ? 'لشهر '.$arabicMonths[$month].($year ? ' '.$year : '') : ($year ? 'لسنة '.$year : 'لجميع الفترات');
    $displayTitle = app()->isLocale('ar') ? 'تقرير مصروفات الإدارات '.$arabicPeriod : 'Administration Expense Report '.$period;
    $logoPath = public_path('images/report-logo.png');
    $logoData = file_exists($logoPath) ? 'data:image/png;base64,'.base64_encode(file_get_contents($logoPath)) : null;
@endphp
<table class="report-head"><tr><td class="date"><span>{{ strtoupper(__('Report date')) }}</span><strong>{{ now()->format('Y/m/d') }}</strong></td><td class="title">{{ $displayTitle }}</td><td class="logo-cell"><div class="logo">@if($logoData)<img src="{{ $logoData }}">@endif</div></td></tr></table>
<table class="data-table"><thead><tr><th class="index">#</th><th class="month">{{ __('Month') }}</th><th class="company">{{ __('Company') }}</th><th class="business">{{ __('Business Field') }}</th><th class="admin">{{ __('Administration') }}</th><th class="location">{{ __('Location') }}</th><th class="refs">WO / SA / TO</th><th class="money">{{ __('Expenses') }}</th><th class="rate">{{ __('Ex Rate') }}</th><th class="total">{{ __('Total LYD') }}</th><th class="received">{{ __('Received') }}</th><th class="returned">{{ __('Returned to Financial') }}</th><th class="notes">{{ __('Remarks') }}</th></tr></thead>
<tbody>@forelse($invoices as $invoice)<tr><td>{{ $loop->iteration }}</td><td>{{ app()->isLocale('ar') ? $arabicMonths[$invoice->invoice_month].' '.$invoice->invoice_year : $invoice->invoice_date->format('F Y') }}</td><td>{{ $invoice->company->name }}</td><td>{{ $invoice->company->business_field ?: '—' }}</td><td>{{ $invoice->administration?->name ?? '—' }}</td><td>{{ $invoice->location }}</td><td>{{ $invoice->agreement_references }}</td><td>{{ number_format($invoice->amount,2) }}</td><td>{{ number_format($invoice->exchange_rate,6) }}</td><td><strong>{{ number_format($invoice->total_lyd,2) }}</strong></td><td>{{ $invoice->received_date?->format('Y/m/d') ?? '—' }}</td><td>{{ $invoice->financial_return_date?->format('Y/m/d') ?? '—' }}</td><td>{{ $invoice->notes ?: '—' }}</td></tr>@empty<tr><td colspan="13">{{ __('No invoices match these filters.') }}</td></tr>@endforelse</tbody></table>
<table class="summary"><tr><td><span>{{ __('Total invoices') }}</span><strong>{{ number_format($invoices->count()) }}</strong></td><td><span>{{ __('Total expenses') }}</span><strong>{{ number_format($invoices->sum('amount'),2) }}</strong></td><td><span>{{ __('Total LYD') }}</span><strong>{{ number_format($invoices->sum(fn($invoice) => $invoice->total_lyd),2) }} {{ __('LYD') }}</strong></td></tr></table>
<div class="footer"><span class="left">InvoicePro</span><span class="right">{{ __('Confidential internal report') }}</span></div>
</body></html>
