<div class="page report-page"><header class="page-header"><div><h1>Reports</h1><p>Build, review, and export invoice reports.</p></div><a class="btn primary" href="{{ route('invoices') }}" wire:navigate>+ New invoice</a></header>
<div class="report-tabs">@foreach(['monthly'=>'Monthly','yearly'=>'Yearly','company'=>'Company','location'=>'Location'] as $key=>$label)<button wire:click="$set('type','{{ $key }}')" class="{{ $type===$key?'active':'' }}">{{ $label }}</button>@endforeach</div>
<section class="filter-panel"><div class="filter-grid"><label>Year<select wire:model.live="year"><option value="">All years</option>@for($y=now()->year+1;$y>=2020;$y--)<option value="{{ $y }}">{{ $y }}</option>@endfor</select></label>
@if($type!=='yearly')<label>Month<select wire:model.live="month"><option value="">All months</option>@foreach(range(1,12) as $m)<option value="{{ $m }}">{{ DateTime::createFromFormat('!m',$m)->format('F') }}</option>@endforeach</select></label>@endif
@if($type==='company')<label>Company<select wire:model.live="companyId"><option value="">Select company</option>@foreach($companies as $company)<option value="{{ $company->id }}">{{ $company->name }}</option>@endforeach</select></label>@endif
@if($type==='location')<label>Location<select wire:model.live="location"><option value="">Select location</option>@foreach($locations as $item)<option>{{ $item }}</option>@endforeach</select></label>@endif
<label class="grow">Search invoices<input wire:model.live.debounce.300ms="search" placeholder="Invoice, company, or location"></label><label>Sort by<select wire:model.live="sort"><option value="date">Date</option><option value="amount">Amount</option><option value="company">Company</option><option value="location">Location</option></select></label></div></section>
<section class="panel report-panel"><div class="exportbar"><strong>{{ ucfirst($type) }} report</strong><div><a class="btn compact preview-button" href="{{ route('reports.print',$this->filters()) }}">Preview &amp; Print</a><span>Export</span>@foreach(['pdf'=>'PDF','xlsx'=>'Excel','csv'=>'CSV'] as $format=>$label)<a class="btn compact" href="{{ route('reports.export',array_merge(['format'=>$format],$this->filters())) }}">{{ $label }}</a>@endforeach</div></div>
<div class="table-wrap"><table><thead><tr><th>Month</th><th>Company</th><th>Location</th><th>WO / SA &amp; TO</th><th>Expenses</th><th>Ex Rate</th><th>Total LYD</th><th>Remarks</th></tr></thead><tbody>
@forelse($invoices as $invoice)<tr><td>{{ $invoice->invoice_date->format('F Y') }}</td><td>{{ $invoice->company->name }}</td><td>{{ $invoice->location }}</td><td>{{ $invoice->agreement_references }}</td><td>{{ number_format($invoice->amount,2) }}</td><td>{{ number_format($invoice->exchange_rate,6) }}</td><td class="lyd-total">{{ number_format($invoice->total_lyd,2) }} LYD</td><td class="remarks">{{ $invoice->notes ?: '—' }}</td></tr>@empty<tr><td colspan="8"><div class="empty">No invoices match these filters.</div></td></tr>@endforelse
</tbody></table></div>
<div class="totals"><div><span>Total invoices</span><strong>{{ number_format($totals->count) }}</strong></div><div><span>Total expenses</span><strong>{{ number_format($totals->expenses,2) }}</strong></div><div><span>Total LYD</span><strong>{{ number_format($totals->total_lyd,2) }} LYD</strong></div></div><div class="pagination">{{ $invoices->links() }}</div></section></div>
