<div class="page report-page"><header class="page-header"><div><h1>{{ __('Reports') }}</h1><p>{{ __('Build, review, and export invoice reports.') }}</p></div><a class="btn primary" href="{{ route('invoices') }}" wire:navigate>{{ __('+ New invoice') }}</a></header>
<div class="report-tabs">@foreach(['monthly'=>'Monthly','yearly'=>'Yearly','company'=>'Company','location'=>'Location'] as $key=>$label)<button wire:click="$set('type','{{ $key }}')" class="{{ $type===$key?'active':'' }}">{{ __($label) }}</button>@endforeach</div>
<section class="filter-panel"><div class="filter-grid"><label>{{ __('Year') }}<select wire:model.live="year"><option value="">{{ __('All years') }}</option>@for($y=now()->year+1;$y>=2020;$y--)<option value="{{ $y }}">{{ $y }}</option>@endfor</select></label>
@if($type!=='yearly')<label>{{ __('Month') }}<select wire:model.live="month"><option value="">{{ __('All months') }}</option>@foreach(range(1,12) as $m)<option value="{{ $m }}">{{ __(DateTime::createFromFormat('!m',$m)->format('F')) }}</option>@endforeach</select></label>@endif
@if($type==='company')<label>{{ __('Company') }}<select wire:model.live="companyId"><option value="">{{ __('Select company') }}</option>@foreach($companies as $company)<option value="{{ $company->id }}">{{ $company->name }}</option>@endforeach</select></label>@endif
@if($type==='location')<label>{{ __('Location') }}<select wire:model.live="location"><option value="">{{ __('Select location') }}</option>@foreach($locations as $item)<option>{{ $item }}</option>@endforeach</select></label>@endif
<label class="grow">{{ __('Search invoices') }}<input wire:model.live.debounce.300ms="search" placeholder="{{ __('Invoice, company, or location') }}"></label><label>{{ __('Sort by') }}<select wire:model.live="sort"><option value="date">{{ __('Date') }}</option><option value="amount">{{ __('Amount') }}</option><option value="company">{{ __('Company') }}</option><option value="location">{{ __('Location') }}</option></select></label></div></section>
<section class="panel report-panel"><div class="exportbar"><strong>{{ __(ucfirst($type)) }} {{ __('report') }}</strong><div><a class="btn compact preview-button" href="{{ route('reports.print',$this->filters()) }}">{{ __('Preview & Print') }}</a><span>{{ __('Export') }}</span>@foreach(['pdf'=>'PDF','xlsx'=>'Excel','csv'=>'CSV'] as $format=>$label)<a class="btn compact" href="{{ route('reports.export',array_merge(['format'=>$format],$this->filters())) }}">{{ __($label) }}</a>@endforeach</div></div>
<div class="table-wrap"><table><thead><tr><th>{{ __('Month') }}</th><th>{{ __('Company') }}</th><th>{{ __('Business Field') }}</th><th>{{ __('Administration') }}</th><th>{{ __('Location') }}</th><th>{{ __('WO / SA & TO') }}</th><th>{{ __('Expenses') }}</th><th>{{ __('Ex Rate') }}</th><th>{{ __('Total LYD') }}</th><th>{{ __('Received') }}</th><th>{{ __('Returned to Financial') }}</th><th>{{ __('Remarks') }}</th></tr></thead><tbody>
@forelse($invoices as $invoice)<tr><td>{{ __( $invoice->invoice_date->format('F')) }} {{ $invoice->invoice_year }}</td><td>{{ $invoice->company->name }}</td><td>{{ $invoice->company->business_field ?: '—' }}</td><td>{{ $invoice->administration?->name ?? '—' }}</td><td>{{ $invoice->location }}</td><td>{{ $invoice->agreement_references }}</td><td>{{ number_format($invoice->amount,2) }}</td><td>{{ number_format($invoice->exchange_rate,6) }}</td><td class="lyd-total">{{ number_format($invoice->total_lyd,2) }} {{ __('LYD') }}</td><td>{{ $invoice->received_date?->format('Y/m/d') ?? '—' }}</td><td>{{ $invoice->financial_return_date?->format('Y/m/d') ?? '—' }}</td><td class="remarks">{{ $invoice->notes ?: '—' }}</td></tr>@empty<tr><td colspan="12"><div class="empty">{{ __('No invoices match these filters.') }}</div></td></tr>@endforelse
</tbody></table></div>
<div class="totals"><div><span>{{ __('Total invoices') }}</span><strong>{{ number_format($totals->count) }}</strong></div><div><span>{{ __('Total expenses') }}</span><strong>{{ number_format($totals->expenses,2) }}</strong></div><div><span>{{ __('Total LYD') }}</span><strong>{{ number_format($totals->total_lyd,2) }} {{ __('LYD') }}</strong></div></div><div class="pagination">{{ $invoices->links() }}</div></section></div>
